services:
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock-api-server
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=production
      - PORT=7001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:7001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
